### ISSUE TITLE
SyntaxError: Error parsing .\anti-raid-master\package.json

### ISSUE THREAD

**Issue by Ailcope** [Emmanuel-Novus/anti-raid#2]
Bonjour,
J'ai essayé d'utiliser votre bot anti raid, mais le problème est que celui ci me retourne une erreur.
J'ai bel et bien mis le token dans le fichier approprié.
Voici l'erreur:
"SyntaxError: Error parsing .\anti-raid-master\package.json: Unexpected string in JSON at position 210
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:262:20)
    at readPackageScope (internal/modules/cjs/loader.js:287:19)
    at shouldUseESMLoader (internal/modules/run_main.js:36:15)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
    at internal/main/run_main_module.js:17:47 {
  path: '.\\anti-raid-master\\package.json'
}
Process exited with code 1"
Le soucis est qu'il n'y a pas autant de ligne...
Sauriez-vous m'aider ?

**Comment by Emmanuel-Novus-zz** [comment]
Delete the package.json file and install the modules one by one manually.

**Comment by Ailcope** [comment]
What's the package to install ?

**Comment by Emmanuel-Novus-zz** [comment]
You need to install colors; discord.js; moment and mysql2 with the command `npm install`!

**Comment by Ailcope** [comment]
Okay, thx, i have install DJS before, so i go install others

**Comment by Ailcope** [comment]
I can't install "colors", the module doesn't exist :/

**Comment by Ailcope** [comment]
My bad, i have do "node install"

**Comment by Ailcope** [comment]
![image](https://user-images.githubusercontent.com/54411234/91457964-45f1f280-e885-11ea-9936-a2a281e6c7bd.png)
Uh, i have install all of modules, but, it doesn't work :( ....

**Comment by TheFinality** [comment]
LEARN JS

**Comment by Ailcope** [comment]
I know js lmao but i haven't understand the fonctionement of this bot :z
